DROP TABLE IF EXISTS deviceTypes;
CREATE TABLE deviceTypes	(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL);

DROP TABLE IF EXISTS devices;
CREATE TABLE devices		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, 
				OwnerId INTEGER REFERENCES people (ID) ON DELETE RESTRICT MATCH SIMPLE NOT NULL, 
				LinkedName VARCHAR NOT NULL,
				Name VARCHAR NOT NULL, 
				deviceType INTEGER NOT NULL REFERENCES deviceTypes (ID) ON DELETE RESTRICT MATCH SIMPLE);

DROP TABLE IF EXISTS eventTypes;
CREATE TABLE eventTypes		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL);

DROP TABLE IF EXISTS eventrelations;
CREATE TABLE eventrelations	(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL, 
				Type INTEGER NOT NULL REFERENCES eventTypes (ID) ON DELETE RESTRICT MATCH SIMPLE);

DROP TABLE IF EXISTS relationTypes;
CREATE TABLE relationTypes	(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL);

DROP TABLE IF EXISTS peoplerelations;
CREATE TABLE peoplerelations	(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL,
				RelationType INTEGER NOT NULL REFERENCES relationTypes (ID) ON DELETE RESTRICT MATCH SIMPLE);

DROP TABLE IF EXISTS people;
CREATE TABLE people		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL, 
				FullName VARCHAR NOT NULL, 
				RelationId INTEGER NOT NULL REFERENCES peoplerelations (ID) ON DELETE RESTRICT MATCH SIMPLE, 
				RelPersonID INTEGER NOT NULL REFERENCES people (ID) ON DELETE RESTRICT MATCH SIMPLE);

DROP TABLE IF EXISTS placeTypes;
CREATE TABLE placeTypes		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL);

DROP TABLE IF EXISTS places;
CREATE TABLE places		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL, 
				Type INTEGER NOT NULL REFERENCES placeTypes (ID) ON DELETE RESTRICT MATCH SIMPLE);
DROP TABLE IF EXISTS params;
CREATE TABLE params     	(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL, 
				Value VARCHAR NOT NULL);

DROP TABLE IF EXISTS fsImage;
CREATE TABLE fsImage		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL,
				ExifVersion		VARCHAR NOT NULL, 
				Make			VARCHAR NOT NULL,
				Model			VARCHAR NOT NULL,
				DateTimeOriginal	VARCHAR NOT NULL,
				Orientation		VARCHAR NOT NULL,
				GpsLatitude		VARCHAR NOT NULL,
				GpsLongitude		VARCHAR NOT NULL,
				GpsAltitude		VARCHAR NOT NULL,
				ImageWidth		VARCHAR NOT NULL,
				ImageLength		VARCHAR NOT NULL,
				BitsPerSample		VARCHAR NOT NULL,
				ExposureTime		VARCHAR NOT NULL,
				FNumber			VARCHAR NOT NULL,
				ISOSpeedRatings		VARCHAR NOT NULL,
				MaxApertureValue	VARCHAR NOT NULL,
				Flash			VARCHAR NOT NULL,
				ExposureProgram		VARCHAR NOT NULL,
				WhiteBalance		VARCHAR NOT NULL,
				DigitalZoomRatio	VARCHAR NOT NULL,
				MeteringMode		VARCHAR NOT NULL,
				FocalLength		VARCHAR NOT NULL,
				ExposureBiasValue	VARCHAR NOT NULL,
				CompressedBitsPerPixel	VARCHAR NOT NULL,
				ColorSpace		VARCHAR NOT NULL,
				ResolutionUnit		VARCHAR NOT NULL,
        			XResolution		VARCHAR NOT NULL,
				YResolution		VARCHAR NOT NULL,
				FocalLengthIn35mmFilm	VARCHAR NOT NULL,
				BrightnessValue		VARCHAR NOT NULL
				);		

DROP TABLE IF EXISTS fsVideo;
CREATE TABLE fsVideo 		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL,
				Length			VARCHAR NOT NULL,
				FrameWidth		VARCHAR NOT NULL,
				FrameHeight		VARCHAR NOT NULL,
				DataRate		VARCHAR NOT NULL,
				TotalBitrate		VARCHAR NOT NULL,
				FrameRate		VARCHAR NOT NULL);

DROP TABLE IF EXISTS fsAudio;
CREATE TABLE fsAudio 		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL,
				Length			VARCHAR NOT NULL,
				Bitrate			VARCHAR NOT NULL,
				Channels		VARCHAR NOT NULL,
				sampleRate		VARCHAR NOT NULL);

DROP TABLE IF EXISTS fvaFolder;
CREATE TABLE fvaFolder		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL,
				DevId INTEGER NOT NULL REFERENCES devices (ID) ON DELETE RESTRICT MATCH SIMPLE,
				Tags		VARCHAR,
				People		VARCHAR,
				PlaceId INTEGER REFERENCES places (ID) ON DELETE RESTRICT MATCH SIMPLE,
				EventId INTEGER REFERENCES eventrelations (ID) ON DELETE RESTRICT MATCH SIMPLE,
				ReasonPeople	VARCHAR,   
				LinkedFolder	VARCHAR,
				whoTookFotoId   INTEGER REFERENCES people (ID) ON DELETE RESTRICT MATCH SIMPLE, 
				ScanerId INTEGER REFERENCES devices (ID) ON DELETE RESTRICT MATCH SIMPLE
				);

DROP TABLE IF EXISTS fvaFile;
CREATE TABLE fvaFile		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL,
				PlaceId INTEGER REFERENCES places (ID) ON DELETE RESTRICT MATCH SIMPLE,
				People		VARCHAR,
				DevId INTEGER NOT NULL REFERENCES devices (ID) ON DELETE RESTRICT MATCH SIMPLE,
                                Description	VARCHAR,
				ScanerId INTEGER REFERENCES devices (ID) ON DELETE RESTRICT MATCH SIMPLE,
                                Comment		VARCHAR,
				OldName		VARCHAR,
				WhoTook		INTEGER REFERENCES people (ID) ON DELETE RESTRICT MATCH SIMPLE,
				OldName1	VARCHAR 
                                );

DROP TABLE IF EXISTS fva;
CREATE TABLE fva         	(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL,
				Path VARCHAR NOT NULL,
				Type		INTEGER NOT NULL,  -- see FVA_FS_TYPE for details
				ReadOnly	INTEGER NOT NULL, -- 0-no, 2-yes
				Size		INTEGER NOT NULL,
				DataModified	VARCHAR NOT NULL,
				DataCreated	VARCHAR NOT NULL,
				FvaFileId INTEGER REFERENCES fvaFile (ID) ON DELETE RESTRICT MATCH SIMPLE,
				FvaFolderId INTEGER REFERENCES fvaFolder (ID) ON DELETE RESTRICT MATCH SIMPLE,
				FsImageId INTEGER REFERENCES fsImage (ID) ON DELETE RESTRICT MATCH SIMPLE,
				FsVideoId INTEGER REFERENCES fsVideo (ID) ON DELETE RESTRICT MATCH SIMPLE,
				FsAudioId INTEGER REFERENCES fsAudio (ID) ON DELETE RESTRICT MATCH SIMPLE );
