DROP TABLE IF EXISTS fvaDeviceTypes;
CREATE TABLE fvaDeviceTypes	(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL);

DROP TABLE IF EXISTS fvaDevices;
CREATE TABLE fvaDevices		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, 
				OwnerId INTEGER REFERENCES people (ID) ON DELETE RESTRICT MATCH SIMPLE NOT NULL, 
				LinkedName VARCHAR NOT NULL,
				Name VARCHAR NOT NULL, 
				fvaDeviceType INTEGER NOT NULL REFERENCES deviceTypes (ID) ON DELETE RESTRICT MATCH SIMPLE);

DROP TABLE IF EXISTS fvaEventTypes;
CREATE TABLE fvaEventTypes		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL);

DROP TABLE IF EXISTS fvaEventRelations;
CREATE TABLE fvaEventrelations	(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL, 
				Type INTEGER NOT NULL REFERENCES eventTypes (ID) ON DELETE RESTRICT MATCH SIMPLE);

DROP TABLE IF EXISTS fvaRelationTypes;
CREATE TABLE fvaRelationTypes	(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL);

DROP TABLE IF EXISTS fvaPeopleRelations;
CREATE TABLE fvaPeopleRelations	(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL,
				RelationType INTEGER NOT NULL REFERENCES fvaRelationTypes (ID) ON DELETE RESTRICT MATCH SIMPLE);

DROP TABLE IF EXISTS fvaPeople;
CREATE TABLE fvaPeople		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL, 
				FullName VARCHAR NOT NULL, 
				RelationId INTEGER NOT NULL REFERENCES fvaPeopleRelations (ID) ON DELETE RESTRICT MATCH SIMPLE, 
				RelPersonID INTEGER NOT NULL REFERENCES fvaPeople (ID) ON DELETE RESTRICT MATCH SIMPLE);

DROP TABLE IF EXISTS fvaPlaceTypes;
CREATE TABLE fvaPlaceTypes	(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL);

DROP TABLE IF EXISTS fvaPlaces;
CREATE TABLE fvaPlaces		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL, 
				Type INTEGER NOT NULL REFERENCES fvaPlaceTypes (ID) ON DELETE RESTRICT MATCH SIMPLE);
DROP TABLE IF EXISTS fvaParams;
CREATE TABLE fvaParams     	(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL, 
				Value VARCHAR NOT NULL);

DROP TABLE IF EXISTS fvaFolder;
CREATE TABLE fvaFolder		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL,
				DevId INTEGER NOT NULL REFERENCES devices (ID) ON DELETE RESTRICT MATCH SIMPLE,
				Tags		VARCHAR,
				People		VARCHAR,
				PlaceId INTEGER REFERENCES places (ID) ON DELETE RESTRICT MATCH SIMPLE,
				EventId INTEGER REFERENCES eventrelations (ID) ON DELETE RESTRICT MATCH SIMPLE,
				ReasonPeople	VARCHAR,   
				LinkedFolder	VARCHAR,
				whoTookFotoId   INTEGER REFERENCES people (ID) ON DELETE RESTRICT MATCH SIMPLE, 
				ScanerId INTEGER REFERENCES devices (ID) ON DELETE RESTRICT MATCH SIMPLE
				);

DROP TABLE IF EXISTS fvaFile;
CREATE TABLE fvaFile		(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL,
				PlaceId INTEGER REFERENCES places (ID) ON DELETE RESTRICT MATCH SIMPLE,
				People		VARCHAR,
				DevId INTEGER NOT NULL REFERENCES devices (ID) ON DELETE RESTRICT MATCH SIMPLE,
                                Description	VARCHAR,
				ScanerId INTEGER REFERENCES devices (ID) ON DELETE RESTRICT MATCH SIMPLE,
                                Comment		VARCHAR,
				OldName		VARCHAR,
				WhoTook		INTEGER REFERENCES people (ID) ON DELETE RESTRICT MATCH SIMPLE,
				OldName1	VARCHAR 
                                );

DROP TABLE IF EXISTS fva;
CREATE TABLE fva         	(ID INTEGER PRIMARY KEY UNIQUE NOT NULL, Name VARCHAR NOT NULL,
				Path VARCHAR NOT NULL,
				Type		INTEGER NOT NULL,  -- see FVA_FS_TYPE for details
				ReadOnly	INTEGER NOT NULL, -- 0-no, 2-yes
				Size		INTEGER NOT NULL,
				DataModified	VARCHAR NOT NULL,
				DataCreated	VARCHAR NOT NULL,
				FvaFileId INTEGER REFERENCES fvaFile (ID) ON DELETE RESTRICT MATCH SIMPLE,
				FvaFolderId INTEGER REFERENCES fvaFolder (ID) ON DELETE RESTRICT MATCH SIMPLE,
				FsImageId INTEGER REFERENCES fsImage (ID) ON DELETE RESTRICT MATCH SIMPLE,
				FsVideoId INTEGER REFERENCES fsVideo (ID) ON DELETE RESTRICT MATCH SIMPLE,
				FsAudioId INTEGER REFERENCES fsAudio (ID) ON DELETE RESTRICT MATCH SIMPLE );
