BEGIN TRANSACTION;
insert into fvaRelationTypes values (1  ,"Родня");
insert into fvaRelationTypes values (2  ,"Друзья");
insert into fvaRelationTypes values (3  ,"Коллеги");
insert into fvaRelationTypes values (4  ,"Одноклассники/одногрупники");
insert into fvaRelationTypes values (0  ,"Без категории");
insert into fvaPeopleRelations values (1  ,"Ребенок", 1);
insert into fvaPeopleRelations values (2  ,"Супруг/а", 1);
insert into fvaPeopleRelations values (3  ,"Кумовство", 1);
insert into fvaPeopleRelations values (10  ,"Друзья", 2);
COMMIT;