#include "CmdLineTasks.h"

_CLASS_TASK_DECLARATION(CLT_Xml_Convert,false)
_CLASS_TASK_DECLARATION(CLT_Update_File_Description,false)
_CLASS_TASK_DECLARATION(CLT_Convert_Dir_Desc,true)
_CLASS_TASK_DECLARATION(CLT_Rename_File_By_Desc,false)
_CLASS_TASK_DECLARATION(CLT_Desc_To_SQL,false)