sqlite3.exe digikam4.db < 00.initDB.sql
sqlite3.exe digikam4.db < 00.views.sql
sqlite3.exe digikam4.db < 01.eventTypes.sql
sqlite3.exe digikam4.db < 02.eventRelations.sql
sqlite3.exe digikam4.db < 03.placeTypes.sql
sqlite3.exe digikam4.db < 04.places.sql
sqlite3.exe digikam4.db < 05.deviceTypes.sql
sqlite3.exe digikam4.db < 06.relationTypes.sql
sqlite3.exe digikam4.db < 07.peopleRelations.sql
sqlite3.exe digikam4.db < 08.people.sql
sqlite3.exe digikam4.db < 09.devices.sql
sqlite3.exe digikam4.db < 10.params.sql
sqlite3.exe digikam4.db < 11.fva.sql
sqlite3.exe digikam4.db < 12.fvaFolder.sql
sqlite3.exe digikam4.db < 13.fvaFile.sql